name = "MyExample"
uuid = "ae258e82-9b78-4329-9bf8-cc6112911095"
authors = ["Gianluca Filippi"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
